version: '3'
services:
  jenkins:
    image: jenkins:latest
    container_name: jenkins
    restart: always
    ports:
      - 4000:4000
    volumes:
      - ./FOR_JENKINS:/var/jenkins_home
  etcd:  
    image: gcr.io/google_containers/etcd:2.0.9
    network_mode: host
    command: ['/usr/local/bin/etcd', '--bind-addr=0.0.0.0:4001', '--data-dir=/var/etcd/data']
  apiserver:  
    image: geku/hyperkube:v1.0.1
    network_mode: host
    command: ["/hyperkube", "apiserver", "--service-cluster-ip-range=172.17.17.1/24", "--address=127.0.0.1", "--etcd_servers=http://127.0.0.1:4001", "--cluster_name=kubernetes", "--v=2"]
  controller:  
    image: geku/hyperkube:v1.0.1
    network_mode: host
    command: ["/hyperkube", "controller-manager", "--master=127.0.0.1:8080", "--v=2"]
  scheduler:  
    image: geku/hyperkube:v1.0.1
    network_mode: host
    command: ["/hyperkube", "scheduler", "--master=127.0.0.1:8080", "--v=2"]
  kubelet:  
    image: geku/hyperkube:v1.0.1
    network_mode: host
    command: ['/hyperkube', 'kubelet', '--api_servers=http://127.0.0.1:8080', '--v=2', '--address=0.0.0.0', '--enable_server']
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  proxy:  
    image: geku/hyperkube:v1.0.1
    network_mode: host
    command: ['/hyperkube', 'proxy', '--master=http://127.0.0.1:8080', '--v=2']
    privileged: true